# Site settings
title: Josh Reeder-Esparza
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joshre.com" # the base hostname & protocol for your site
github_username: joshre
description: Full-stack developer, engineer, and designer with over a decade of experience building highly performant websites.
permalink: /blog/:title/
# Build settings
markdown: kramdown

sass:
  style: :compressed

collections:
  things:
    output: false
  share:
    output: true
